### PR TITLE
docs: added pr template for contributing a pr

### PR DESCRIPTION
**Pull request by ezesundayeze**
We need to have a template for contributing a pr so we ensure that all checks are passed before merging

### CODE REVIEW

**Comment by Ani-Emmanuel** [comment]
pr-template is empty

**Comment by ezesundayeze** [comment]
> pr-template is empty

Ah, my bad.

**Comment by ezesundayeze** [comment]
And I added rollup and it slip through. It seems like you didn't see that

**Comment by Ani-Emmanuel** [comment]
i dont understand what do you mean by rollup

**Comment by Ani-Emmanuel** [comment]
Ok refreshed now and i saw some write up

**Comment by ezesundayeze** [comment]
So, apparently there was a conflict. I just fixed the conflict and merged.

**Comment by ezesundayeze** [comment]
Can you check now if you can find the pr-template?

**Comment by Ani-Emmanuel** [comment]
ok let me merge it

**Pull request merged**
